# Generated by Django 2.2 on 2022-03-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrders',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.DateTimeField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('delivered_to_city', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['transaction_id'],
            },
        ),
    ]
